# Generated by Django 4.1.3 on 2022-11-10 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('direccion', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('creado', models.DateField(auto_now_add=True)),
                ('pagado', models.BooleanField()),
                ('precio_compra', models.IntegerField()),
                ('estado', models.CharField(choices=[('pedido', 'Pedido'), ('enviado', 'Enviado')], default='pedido', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item_Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='Orden.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='Producto.producto')),
            ],
        ),
    ]
