# Generated by Django 4.1.3 on 2022-11-15 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Orden', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='creado',
            new_name='fecha_pedido',
        ),
        migrations.RemoveField(
            model_name='item_pedido',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='primer_nombre',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='telefono',
        ),
        migrations.AddField(
            model_name='item_pedido',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(to='Orden.item_pedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
