# Generated by Django 4.1.3 on 2022-11-17 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orden', '0002_rename_creado_pedido_fecha_pedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_pedido',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='productos',
        ),
        migrations.AddField(
            model_name='item_pedido',
            name='pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Orden.pedido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item_pedido',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
