# Generated by Django 4.1.1 on 2023-05-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orden', '0003_remove_item_pedido_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pagado',
            field=models.BooleanField(null=True),
        ),
    ]
