# Generated by Django 4.1.1 on 2023-05-12 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orden', '0004_alter_pedido_pagado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_pedido',
            old_name='user',
            new_name='nombre',
        ),
    ]
