# Generated by Django 4.1.1 on 2023-05-12 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orden', '0005_rename_user_item_pedido_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='user',
            new_name='nombre',
        ),
    ]
