# Generated by Django 4.1.1 on 2023-05-12 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orden', '0006_rename_user_pedido_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_pedido',
            old_name='nombre',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='nombre',
            new_name='user',
        ),
    ]
